//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICT3104_Group4_SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Module
    {
        public Module()
        {
            this.Lecturer_Module = new HashSet<Lecturer_Module>();
            
        }
    
        public int Id { get; set; }
        [Display(Name = "Module Name")]
        [StringLength(20)]
        [Required]
        public string name { get; set; }
        [DefaultValue("Created")]
        public string status { get; set; }
        public Nullable<System.DateTime> frozenDateTime { get; set; }
        public Nullable<System.DateTime> publishDateTime { get; set; }
        [Display(Name = "Year")]
        public int year { get; set; }
        public string hodId { get; set; }
        public string lecturerId { get; set; }    
        public virtual ICollection<Lecturer_Module> Lecturer_Module { get; set; }

    }
}
