//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICT3104_Group4_SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Programme
    {
        public Programme()
        {
            this.Module_Programme = new HashSet<Module_Programme>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Programme Name")]
        public string programmeName { get; set; }
        public string lecturerId { get; set; }
    
        public virtual ICollection<Module_Programme> Module_Programme { get; set; }
    }
}
