////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated from a template.
////
////     Manual changes to this file may cause unexpected behavior in your application.
////     Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace ICT3104_Group4_SMS.Models
//{
//    using System;
//    using System.Data.Entity;
//    using System.Data.Entity.Infrastructure;
    
//    public partial class SMSEntities : DbContext
//    {
//        public SMSEntities()
//            : base("name=SMSEntities")
//        {
//        }
    
//        protected override void OnModelCreating(DbModelBuilder modelBuilder)
//        {
//            throw new UnintentionalCodeFirstException();
//        }
    
//        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
//        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
//        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
//        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
//        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
//        public virtual DbSet<Class> Classes { get; set; }
//        public virtual DbSet<Module> Modules { get; set; }
//        public virtual DbSet<Programme> Programmes { get; set; }
//        public virtual DbSet<Recommendation> Recommendations { get; set; }
//    }
//}
