// <auto-generated />
namespace ICT3104_Group4_SMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class recStringLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recStringLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201611301554042_recStringLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
